const league = {
  fixture_id: 605176,
  league_id: 2833,
  league: {
    name: "Primera Division",
    country: "Spain",
    logo: "https://media.api-sports.io/football/leagues/140.png",
    flag: "https://media.api-sports.io/flags/es.svg",
  },
  event_date: "2020-12-04T20:00:00+00:00",
  event_timestamp: 1607112000,
  firstHalfStart: null,
  secondHalfStart: null,
  round: "Regular Season - 12",
  status: "Not Started",
  statusShort: "NS",
  elapsed: 0,
  venue: "San Mamés Barria",
  referee: null,
  homeTeam: {
    team_id: 531,
    team_name: "Athletic Club",
    logo: "https://media.api-sports.io/football/teams/531.png",
  },
  awayTeam: {
    team_id: 538,
    team_name: "Celta Vigo",
    logo: "https://media.api-sports.io/football/teams/538.png",
  },
  goalsHomeTeam: null,
  goalsAwayTeam: null,
  score: { halftime: null, fulltime: null, extratime: null, penalty: null },
};

const fixtureStats = {
  api: {
    results: 1,
    predictions: [
      {
        match_winner: "1 N",
        under_over: null,
        goals_home: "-2.5",
        goals_away: "-1.5",
        advice: "Double chance : Athletic Club or draws",
        winning_percent: {
          home: "45%",
          draws: "45%",
          away: "10%",
        },
        teams: {
          home: {
            team_id: 531,
            team_name: "Athletic Club",
            last_5_matches: {
              forme: "47%",
              att: "57%",
              def: "64%",
              goals: 8,
              goals_avg: 1.6,
              goals_against: 5,
              goals_against_avg: 1,
            },
            all_last_matches: {
              matchs: {
                matchsPlayed: {
                  home: 4,
                  away: 6,
                  total: 10,
                },
                wins: {
                  home: 3,
                  away: 1,
                  total: 4,
                },
                draws: {
                  home: 0,
                  away: 1,
                  total: 1,
                },
                loses: {
                  home: 1,
                  away: 4,
                  total: 5,
                },
              },
              goals: {
                goalsFor: {
                  home: 8,
                  away: 4,
                  total: 12,
                },
                goalsAgainst: {
                  home: 2,
                  away: 8,
                  total: 10,
                },
              },
              goalsAvg: {
                goalsFor: {
                  home: "2.0",
                  away: "0.7",
                  total: "1.2",
                },
                goalsAgainst: {
                  home: "0.5",
                  away: "1.3",
                  total: "1.0",
                },
              },
            },
            last_h2h: {
              played: {
                home: 8,
                away: 8,
                total: 16,
              },
              wins: {
                home: 5,
                away: 4,
                total: 9,
              },
              draws: {
                home: 3,
                away: 2,
                total: 5,
              },
              loses: {
                home: 0,
                away: 2,
                total: 2,
              },
            },
          },
          away: {
            team_id: 538,
            team_name: "Celta Vigo",
            last_5_matches: {
              forme: "33%",
              att: "57%",
              def: "21%",
              goals: 8,
              goals_avg: 1.6,
              goals_against: 11,
              goals_against_avg: 2.2,
            },
            all_last_matches: {
              matchs: {
                matchsPlayed: {
                  home: 5,
                  away: 6,
                  total: 11,
                },
                wins: {
                  home: 2,
                  away: 0,
                  total: 2,
                },
                draws: {
                  home: 0,
                  away: 4,
                  total: 4,
                },
                loses: {
                  home: 3,
                  away: 2,
                  total: 5,
                },
              },
              goals: {
                goalsFor: {
                  home: 6,
                  away: 5,
                  total: 11,
                },
                goalsAgainst: {
                  home: 11,
                  away: 9,
                  total: 20,
                },
              },
              goalsAvg: {
                goalsFor: {
                  home: "1.2",
                  away: "0.8",
                  total: "1.0",
                },
                goalsAgainst: {
                  home: "2.2",
                  away: "1.5",
                  total: "1.8",
                },
              },
            },
            last_h2h: {
              played: {
                home: 8,
                away: 8,
                total: 16,
              },
              wins: {
                home: 2,
                away: 0,
                total: 2,
              },
              draws: {
                home: 2,
                away: 3,
                total: 5,
              },
              loses: {
                home: 4,
                away: 5,
                total: 9,
              },
            },
          },
        },
        h2h: [
          {
            fixture_id: 204623,
            league_id: 733,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2012-12-09T16:00:00+00:00",
            event_timestamp: 1355068800,
            firstHalfStart: 1355068800,
            secondHalfStart: 1355072400,
            round: "Regular Season - 15",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Estadio San Mamés (Bilbao)",
            referee: null,
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 0,
            score: {
              halftime: "1-0",
              fulltime: "1-0",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 204807,
            league_id: 733,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2013-05-03T19:00:00+00:00",
            event_timestamp: 1367607600,
            firstHalfStart: 1367607600,
            secondHalfStart: 1367611200,
            round: "Regular Season - 34",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Estadio de Balaídos (Vigo)",
            referee: null,
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 1,
            score: {
              halftime: "0-1",
              fulltime: "1-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 204136,
            league_id: 732,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2013-09-16T20:00:00+00:00",
            event_timestamp: 1379361600,
            firstHalfStart: 1379361600,
            secondHalfStart: 1379365200,
            round: "Regular Season - 4",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "San Mamés Barria (Bilbao)",
            referee: null,
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 3,
            goalsAwayTeam: 2,
            score: {
              halftime: "1-1",
              fulltime: "3-2",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 204326,
            league_id: 732,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2014-02-10T21:00:00+00:00",
            event_timestamp: 1392066000,
            firstHalfStart: 1392066000,
            secondHalfStart: 1392069600,
            round: "Regular Season - 23",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Estadio de Balaídos (Vigo)",
            referee: null,
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 0,
            goalsAwayTeam: 0,
            score: {
              halftime: "0-0",
              fulltime: "0-0",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 203789,
            league_id: 731,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2014-10-18T16:00:00+00:00",
            event_timestamp: 1413648000,
            firstHalfStart: 1413648000,
            secondHalfStart: 1413651600,
            round: "Regular Season - 8",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "San Mamés Barria (Bilbao)",
            referee: null,
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 1,
            score: {
              halftime: "1-0",
              fulltime: "1-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 203981,
            league_id: 731,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2015-03-14T21:00:00+00:00",
            event_timestamp: 1426366800,
            firstHalfStart: 1426366800,
            secondHalfStart: 1426370400,
            round: "Regular Season - 27",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Municipal de Balaídos",
            referee: "Antonio Mateu, Spain",
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 2,
            score: {
              halftime: "0-2",
              fulltime: "1-2",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 203504,
            league_id: 730,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2015-12-30T19:30:00+00:00",
            event_timestamp: 1451503800,
            firstHalfStart: 1451503800,
            secondHalfStart: 1451507400,
            round: "Regular Season - 17",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Municipal de Balaídos",
            referee: "Pedro Jesus Perez Montero, Spain",
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 0,
            goalsAwayTeam: 1,
            score: {
              halftime: "0-0",
              fulltime: "0-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 203692,
            league_id: 730,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2016-05-01T10:00:00+00:00",
            event_timestamp: 1462096800,
            firstHalfStart: 1462096800,
            secondHalfStart: 1462100400,
            round: "Regular Season - 36",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "San Mamés",
            referee: "Javier Estrada Fernandez, Spain",
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 2,
            goalsAwayTeam: 1,
            score: {
              halftime: "1-1",
              fulltime: "2-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 20665,
            league_id: 64,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2016-12-19T19:45:00+00:00",
            event_timestamp: 1482176700,
            firstHalfStart: 1482176700,
            secondHalfStart: 1482180300,
            round: "Regular Season - 16",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "San Mamés",
            referee: "David Fernandez Borbalan, Spain",
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 2,
            goalsAwayTeam: 1,
            score: {
              halftime: "0-0",
              fulltime: "2-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 20476,
            league_id: 64,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2017-04-30T18:45:00+00:00",
            event_timestamp: 1493577900,
            firstHalfStart: 1493577900,
            secondHalfStart: 1493581500,
            round: "Regular Season - 35",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Municipal de Balaídos",
            referee: "David Fernandez Borbalan, Spain",
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 0,
            goalsAwayTeam: 3,
            score: {
              halftime: "0-1",
              fulltime: "0-3",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 9781,
            league_id: 30,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2017-11-05T15:15:00+00:00",
            event_timestamp: 1509894900,
            firstHalfStart: 1509894900,
            secondHalfStart: 1509898500,
            round: "Regular Season - 11",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Municipal de Balaídos",
            referee: "Jesus Gil Manzano, Spain",
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 3,
            goalsAwayTeam: 1,
            score: {
              halftime: "3-1",
              fulltime: "3-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 9596,
            league_id: 30,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2018-03-31T14:15:00+00:00",
            event_timestamp: 1522505700,
            firstHalfStart: 1522505700,
            secondHalfStart: 1522509300,
            round: "Regular Season - 30",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "San Mamés",
            referee: "Carlos Del Cerro Grande, Spain",
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 1,
            score: {
              halftime: "0-0",
              fulltime: "1-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 27310,
            league_id: 87,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2019-01-07T20:00:00+00:00",
            event_timestamp: 1546891200,
            firstHalfStart: 1546891200,
            secondHalfStart: 1546894800,
            round: "Regular Season - 18",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Municipal de Balaídos",
            referee: "Juan Martinez Munuera, Spain",
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 2,
            score: {
              halftime: "1-1",
              fulltime: "1-2",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 27499,
            league_id: 87,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2019-05-12T16:30:00+00:00",
            event_timestamp: 1557678600,
            firstHalfStart: 1557678600,
            secondHalfStart: 1557682200,
            round: "Regular Season - 37",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "San Mamés",
            referee: "Javier Estrada Fernandez, Spain",
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 3,
            goalsAwayTeam: 1,
            score: {
              halftime: "3-0",
              fulltime: "3-1",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 214094,
            league_id: 775,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2019-10-06T12:00:00+00:00",
            event_timestamp: 1570363200,
            firstHalfStart: 1570363200,
            secondHalfStart: 1570366800,
            round: "Regular Season - 8",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "Abanca-Balaídos",
            referee: "David Medié",
            homeTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            awayTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 0,
            score: {
              halftime: "0-0",
              fulltime: "1-0",
              extratime: null,
              penalty: null,
            },
          },
          {
            fixture_id: 214212,
            league_id: 775,
            league: {
              name: "Primera Division",
              country: "Spain",
              logo: "https://media.api-sports.io/football/leagues/140.png",
              flag: "https://media.api-sports.io/flags/es.svg",
            },
            event_date: "2020-01-19T17:30:00+00:00",
            event_timestamp: 1579455000,
            firstHalfStart: 1579455000,
            secondHalfStart: 1579458600,
            round: "Regular Season - 20",
            status: "Match Finished",
            statusShort: "FT",
            elapsed: 90,
            venue: "San Mamés Barria",
            referee: "David Medié",
            homeTeam: {
              team_id: 531,
              team_name: "Athletic Club",
              logo: "https://media.api-sports.io/football/teams/531.png",
            },
            awayTeam: {
              team_id: 538,
              team_name: "Celta Vigo",
              logo: "https://media.api-sports.io/football/teams/538.png",
            },
            goalsHomeTeam: 1,
            goalsAwayTeam: 1,
            score: {
              halftime: "0-0",
              fulltime: "1-1",
              extratime: null,
              penalty: null,
            },
          },
        ],
        comparison: {
          forme: {
            home: "58%",
            away: "42%",
          },
          att: {
            home: "50%",
            away: "50%",
          },
          def: {
            home: "69%",
            away: "31%",
          },
          fish_law: {
            home: "86%",
            away: "14%",
          },
          h2h: {
            home: "62%",
            away: "38%",
          },
          goals_h2h: {
            home: "58%",
            away: "42%",
          },
        },
      },
    ],
  },
};
